'use client';
import { useEffect, useRef, useState } from 'react';
import ActivityArtwork from '@/components/ActivityArtwork';
import ZoomWordmark from '@/components/ZoomWordmark';
import { CalendarDays, Clock3, LogOut, Settings, Video, UserRound, X, Copy, Trash2, RotateCcw, PhoneOff, Plus, ChevronLeft, ChevronRight, Pencil, FileText, Circle, Bell, Check, ChevronDown, Undo2, ThumbsUp, ThumbsDown } from 'lucide-react';
import { api, Meeting, User, inviteLink } from '@/lib/api';
import { useRouter } from 'next/navigation';
function fmtTime(s:string|null){if(!s)return '';return new Date(s).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}
export default function Home(){
 const router=useRouter();const [user,setUser]=useState<User|null>(null);const [meetings,setMeetings]=useState<Meeting[]>([]);const [starting,setStarting]=useState(false);const [profile,setProfile]=useState(false);const [toast,setToast]=useState('');const [settings,setSettings]=useState(false);const [active,setActive]=useState<{meetingId:string;title:string;muted?:boolean;cameraOff?:boolean}|null>(null);
 const [presence,setPresence]=useState<'Available'|'Away'|'Busy'>('Available');const [presenceOpen,setPresenceOpen]=useState(false);const [activity,setActivity]=useState(false);const [activityTab,setActivityTab]=useState<'focus'|'other'>('focus');const accountRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!user)return;const saved=localStorage.getItem(`zoom_presence_${user.id}`);if(saved==='Available'||saved==='Away'||saved==='Busy')setPresence(saved)},[user?.id]);
 useEffect(()=>{const dismiss=(e:PointerEvent)=>{if(accountRef.current&&!accountRef.current.contains(e.target as Node)){setProfile(false);setPresenceOpen(false)}};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setProfile(false);setPresenceOpen(false);setActivity(false)}};document.addEventListener('pointerdown',dismiss);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',dismiss);document.removeEventListener('keydown',key)}},[]);
 const choosePresence=(next:'Available'|'Away'|'Busy')=>{setPresence(next);setPresenceOpen(false);localStorage.setItem(`zoom_presence_${user?.id}`,next)};
 const [backgroundMeeting,setBackgroundMeeting]=useState<{meetingId:string;muted?:boolean;cameraOff?:boolean;at:number}|null>(null);const backgroundRef=useRef<HTMLIFrameElement>(null);const handoffUntil=useRef(0);
 useEffect(()=>{if(!user)return;try{const h=JSON.parse(sessionStorage.getItem('zoom_home_handoff')||'null');sessionStorage.removeItem('zoom_home_handoff');if(h&&h.userId===user.id&&Date.now()-h.at<5000){const saved=JSON.parse(localStorage.getItem('zoom_active_meeting')||'{}');handoffUntil.current=Date.now()+5000;setBackgroundMeeting({meetingId:h.meetingId,muted:saved.muted,cameraOff:saved.cameraOff,at:h.at})}}catch{}},[user?.id]);
 useEffect(()=>{const receive=(e:MessageEvent)=>{if(e.origin!==window.location.origin||e.source!==backgroundRef.current?.contentWindow)return;if(e.data?.type==='mini-ended'){setBackgroundMeeting(null);setActive(null);localStorage.removeItem('zoom_active_meeting')}else if(e.data?.type==='mini-media'&&e.data.connected){void api.activeMeeting(user!.id).then(live=>{if(live.active&&live.meeting_id)setActive({meetingId:live.meeting_id,title:'Current meeting',muted:e.data.muted,cameraOff:e.data.cameraOff})})}};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive)},[user?.id]);
 const backToMeeting=()=>{if(!active||!user)return;backgroundRef.current?.contentWindow?.postMessage({type:'mini-release'},window.location.origin);setTimeout(()=>router.push(`/meeting/${active.meetingId}?name=${encodeURIComponent(user.name)}&userId=${user.id}${active.muted!==undefined?`&muted=${active.muted?'1':'0'}`:''}${active.cameraOff!==undefined?`&cameraOff=${active.cameraOff?'1':'0'}`:''}`),100)};
 const [feedbackMeeting,setFeedbackMeeting]=useState('');
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('feedback');if(id){setFeedbackMeeting(id);router.replace('/')}},[router]);
 const saveFeedback=(rating:'great'|'issues')=>{try{const key=`zoom_feedback_${user?.id||0}`;const history=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify([...history,{meetingId:feedbackMeeting,rating,at:new Date().toISOString()}]))}catch{}setFeedbackMeeting('');if(user?.id===0)router.replace('/login')};
 const [now,setNow]=useState(new Date());const [dayOffset,setDayOffset]=useState(0);
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]);
 const [utility,setUtility]=useState<'Recordings'|'Summaries'|'My Notes'|null>(null);const [notes,setNotes]=useState('');const [recordingURL,setRecordingURL]=useState('');
 useEffect(()=>()=>{if(recordingURL)URL.revokeObjectURL(recordingURL)},[recordingURL]);
 const openUtility=(kind:'Recordings'|'Summaries'|'My Notes')=>{setUtility(kind);if(kind==='My Notes')setNotes(localStorage.getItem(`zoom_notes_${user?.id}`)||'')};
 useEffect(()=>{try{const raw=localStorage.getItem('zoom_user');if(!raw){if(new URLSearchParams(window.location.search).has('feedback'))setUser({id:0,name:'Guest',email:''});else router.replace('/login');return}const u=JSON.parse(raw) as User;setUser(u);api.meetings(u.id).then(setMeetings).catch(()=>{});}catch{router.replace('/login')}},[router]);
 useEffect(()=>{if(!user)return;let cancelled=false;const verify=async()=>{try{const live=await api.activeMeeting(user.id);if(cancelled)return;if(!live.active||!live.meeting_id){if(Date.now()<handoffUntil.current)return;setBackgroundMeeting(null);localStorage.removeItem('zoom_active_meeting');setActive(null);return}let saved:{meetingId?:string;title?:string;muted?:boolean;cameraOff?:boolean;userId?:number}={};try{saved=JSON.parse(localStorage.getItem('zoom_active_meeting')||'{}')}catch{}const matches=saved.userId===user.id&&saved.meetingId===live.meeting_id;setActive({meetingId:live.meeting_id,title:matches?saved.title||'Current meeting':'Current meeting',muted:matches?saved.muted:undefined,cameraOff:matches?saved.cameraOff:undefined})}catch{if(!cancelled)setActive(null)}};void verify();const timer=setInterval(verify,2000);window.addEventListener('focus',verify);return()=>{cancelled=true;clearInterval(timer);window.removeEventListener('focus',verify)}},[user?.id]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)};
 const create=async()=>{if(!user||starting)return;setStarting(true);try{const m=await api.create({title:`${user.name}'s Zoom Meeting`,description:'',host_name:user.name,owner_user_id:user.id,is_scheduled:false});enterMeeting(m,true)}catch(e){notify((e as Error).message);setStarting(false)}};
 const enterMeeting=(m:Meeting,host=false)=>{const normalized=m.meeting_id.replaceAll(' ','');localStorage.setItem('zoom_active_meeting',JSON.stringify({meetingId:normalized,title:m.title,host,userId:user?.id}));setActive({meetingId:normalized,title:m.title});router.push(`/meeting/${normalized}?name=${encodeURIComponent(user?.name||'Guest')}&host=${host?'1':'0'}&userId=${user?.id||''}`)};
 const leaveActive=()=>{localStorage.removeItem('zoom_active_meeting');setActive(null);notify('You left the current meeting. You can start or join another meeting now.')};
 const logout=()=>{if(active)return notify('Leave your current meeting before logging out.');localStorage.setItem('zoom_signed_out','1');localStorage.removeItem('zoom_user');localStorage.removeItem('zoom_name');router.replace('/login')};
 if(!user)return null;
 const scheduled=meetings.filter(m=>m.is_scheduled&&m.scheduled_at);const recent=meetings.filter(m=>!m.is_scheduled);
 return <div className="app"><header className="topbar"><div className="brand"><ZoomWordmark/> <span>Workplace</span></div><div className="navright"><button aria-label="Settings" className="iconbtn" onClick={()=>setSettings(true)}><Settings size={18}/><span>Settings</span></button><button className={`activityBell ${activity?'active':''}`} aria-label="Activity Center" title="Activity Center" aria-expanded={activity} onClick={()=>setActivity(v=>!v)}><Bell size={18}/></button><div className="accountControl" ref={accountRef}><button className="accountAvatarButton" aria-label="Account menu" aria-expanded={profile} onClick={()=>{setProfile(v=>!v);setPresenceOpen(false)}}><span className="accountAvatar">{user.name[0]?.toUpperCase()}</span><span className={`presenceBadge ${presence.toLowerCase()}`}>{presence==='Away'&&<Clock3 size={11}/>}</span></button>{profile&&<div className="accountMenu"><div className="accountIdentity"><span className="accountAvatar">{user.name[0]?.toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.email}</small></div></div><button className="presenceRow" aria-expanded={presenceOpen} onClick={()=>setPresenceOpen(v=>!v)}><span className={`presenceSymbol ${presence.toLowerCase()}`}>{presence==='Away'&&<Clock3 size={13}/>}</span>{presence}<ChevronRight size={15}/></button>{presenceOpen&&<div className="presenceOptions">{(['Available','Away','Busy'] as const).map(option=><button key={option} onClick={()=>choosePresence(option)}><span className={`presenceSymbol ${option.toLowerCase()}`}>{option==='Away'&&<Clock3 size={13}/>}</span>{option}{presence===option&&<Check size={14}/>}</button>)}</div>}<div className="accountSeparator"/><button className="accountSignout" onClick={logout}>Sign out</button></div>}</div></div></header>
 {backgroundMeeting&&<iframe ref={backgroundRef} title="Background meeting session" className="backgroundMeetingSession" src={`/meeting/${backgroundMeeting.meetingId}?name=${encodeURIComponent(user.name)}&userId=${user.id}&mini=1${backgroundMeeting.muted!==undefined?`&muted=${backgroundMeeting.muted?'1':'0'}`:''}${backgroundMeeting.cameraOff!==undefined?`&cameraOff=${backgroundMeeting.cameraOff?'1':'0'}`:''}`} allow="camera; microphone; autoplay"/>}
 <main className="page"><div className="workspaceClock"><h1>{now.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</h1><p>{now.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</p></div>
 <div className="heroActions"><button className="action orange" disabled={starting} onClick={active?backToMeeting:create}><div className="round">{active?<Undo2 size={27}/>:<Video size={27}/>}</div><strong>{active?'Back to Meeting':starting?'Starting…':'New meeting'}</strong></button><button className="action blue" disabled={Boolean(active)} onClick={()=>router.push('/join')}><div className="round"><Plus size={29}/></div><strong>Join</strong></button><button className="action blue" onClick={()=>router.push('/schedule')}><div className="round"><CalendarDays size={27}/></div><strong>Schedule</strong></button></div>
 <div className="workspaceShortcuts"><button onClick={()=>openUtility('Recordings')}><span className="shortcutIcon rose"><Circle size={17}/></span>Recordings</button><button onClick={()=>openUtility('Summaries')}><span className="shortcutIcon purple"><FileText size={17}/></span>Summaries</button><button onClick={()=>openUtility('My Notes')}><span className="shortcutIcon purple"><Pencil size={17}/></span>My Notes</button></div>
 <section className="calendarCard"><div className="calendarNotice"><CalendarDays size={19}/><span>Plan your next conversation.<br/><button onClick={()=>{if(active)notify('Leave your current meeting before scheduling another.');else router.push('/schedule')}}>Schedule a meeting</button> and share the invite with your team.</span></div><div className="calendarTitle">{new Date(now.getFullYear(),now.getMonth(),now.getDate()+dayOffset).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</div><div className="calendarNav"><button onClick={()=>setDayOffset(0)}>Today</button><button aria-label="Previous day" onClick={()=>setDayOffset(v=>v-1)}><ChevronLeft size={17}/></button><button aria-label="Next day" onClick={()=>setDayOffset(v=>v+1)}><ChevronRight size={17}/></button></div><div className="calendarContent">{scheduled.filter(m=>new Date(m.scheduled_at!).toDateString()===new Date(now.getFullYear(),now.getMonth(),now.getDate()+dayOffset).toDateString()).map(m=><div className="meetingRow" key={m.meeting_id}><div className="dateBox"><CalendarDays size={20}/></div><div className="meetingInfo"><strong>{m.title}</strong><span>{fmtTime(m.scheduled_at)} · {m.duration_minutes} min</span></div>{!active&&<button className="smallbtn" onClick={()=>enterMeeting(m,true)}>Start</button>}<button className="iconbtn" aria-label={`Copy invite for ${m.title}`} onClick={()=>navigator.clipboard.writeText(inviteLink(m.meeting_id)).then(()=>notify('Invite link copied'))}><Copy size={16}/></button></div>)}{!scheduled.some(m=>new Date(m.scheduled_at!).toDateString()===new Date(now.getFullYear(),now.getMonth(),now.getDate()+dayOffset).toDateString())&&<div className="calendarEmpty"><svg width="118" height="98" viewBox="0 0 118 98" aria-hidden="true"><ellipse cx="58" cy="82" rx="39" ry="10" fill="#f2f1fc"/><path d="M55 18 L15 29 L90 46 Z" fill="#c8c7ed"/><path d="M55 18 L45 38 L90 46 Z" fill="#a4a3d1"/><path d="M55 18 L71 38 L90 46 Z" fill="#e2e2fa"/><path d="M56 35 L46 80" stroke="#bfbfe5" strokeWidth="3"/><path d="M52 69 L84 72 L46 80 Z" fill="#d0cff0"/></svg><p>No meetings scheduled.</p></div>}</div></section>

 <section className="section"><div className="sectionHead"><h2>Recent Meetings</h2></div><div className="card">{recent.map(m=><div className="meetingRow" key={m.meeting_id}><div className="dateBox"><Clock3 size={20}/></div><div className="meetingInfo"><strong>{m.title}</strong><span>Meeting ID {m.meeting_id} · {m.host_name}</span></div>{!active&&<button className="smallbtn" onClick={()=>enterMeeting(m,m.owner_user_id===user.id)}>Rejoin</button>}<button className="iconbtn" onClick={()=>api.delete(m.meeting_id,user.id).then(()=>setMeetings(v=>v.filter(x=>x.meeting_id!==m.meeting_id))).then(()=>notify('Meeting removed'))}><Trash2 size={16}/></button></div>)}{recent.length===0&&<div className="empty">No recent meetings yet.</div>}</div></section></main>
 {activity&&<aside className="activitySidebar" aria-label="Activity Center"><div className="activityHeading"><h2>Activity Center</h2><button aria-label="Close Activity Center" onClick={()=>setActivity(false)}><X size={17}/></button></div><div className="activityTabs" role="tablist" aria-label="Notification category"><button role="tab" id="focus-tab" aria-selected={activityTab==='focus'} aria-controls="activity-content" onClick={()=>setActivityTab('focus')}>Focus</button><button role="tab" id="other-tab" aria-selected={activityTab==='other'} aria-controls="activity-content" onClick={()=>setActivityTab('other')}>Other</button></div><div className="activityContent" id="activity-content" role="tabpanel" aria-labelledby={activityTab==='focus'?'focus-tab':'other-tab'}><ActivityArtwork other={activityTab==='other'}/>{activityTab==='focus'?<><h3>You've cleared your suggestions</h3><p>Check out the rest of your notifications in the Other tab.</p><button className="activitySwitch" onClick={()=>setActivityTab('other')}>View other notifications</button></>:<><h3>You’re all caught up!</h3><p>When there’s new activity, you’ll see it here.</p></>}</div></aside>}
 {feedbackMeeting&&<div className="qualityBackdrop"><div className="qualityDialog" role="dialog" aria-modal="true" aria-labelledby="meeting-quality-title"><button className="qualityClose" aria-label="Close meeting feedback" onClick={()=>{setFeedbackMeeting('');if(user.id===0)router.replace('/login')}}><X size={19}/></button><h2 id="meeting-quality-title">How was your Zoom meeting quality?</h2><div className="qualityOptions"><button onClick={()=>saveFeedback('great')}><span className="qualityGreat"><ThumbsUp size={34} fill="currentColor"/></span>Great</button><button onClick={()=>saveFeedback('issues')}><span className="qualityIssues"><ThumbsDown size={34} fill="currentColor"/></span>Had Issues</button></div><div className="qualityPrivacy" title="Feedback is stored only in this browser.">Who can see your feedback?<span>Only you, in this browser.</span></div></div></div>}
 {utility&&<div className="modalBackdrop"><div className="modal utilityModal"><div className="utilityHeading"><h2>{utility}</h2><button className="iconbtn" aria-label="Close workspace panel" onClick={()=>setUtility(null)}><X size={20}/></button></div>{utility==='My Notes'?<><p className="utilityHint">Private notes saved in this browser for your account.</p><div className="field"><textarea aria-label="My notes" rows={9} value={notes} placeholder="Write your meeting notes…" onChange={e=>setNotes(e.target.value)}/></div><button className="primary" onClick={()=>{localStorage.setItem(`zoom_notes_${user.id}`,notes);notify('Notes saved');setUtility(null)}}>Save notes</button></>:utility==='Summaries'?<><p className="utilityHint">Meeting details and descriptions from your history.</p>{recent.length?recent.map(m=><article className="summaryItem" key={m.id}><strong>{m.title}</strong><p>{m.description||'No description added.'}</p><small>{new Date(m.created_at).toLocaleString()} · {m.host_name}</small></article>):<div className="empty">No meeting history yet.</div>}</>:<><p className="utilityHint">Local recordings download to your computer when you stop recording. Start one from More → Record on this computer inside a meeting.</p><div className="field"><label htmlFor="local-recording">Open a downloaded recording</label><input id="local-recording" type="file" accept="video/*,.webm" onChange={e=>{const file=e.target.files?.[0];if(file)setRecordingURL(URL.createObjectURL(file))}}/></div>{recordingURL?<video className="recordingPreview" controls src={recordingURL}/>:<div className="empty">Choose a local recording to play it here.</div>}</>}</div></div>}
 {settings&&<div className="modalBackdrop"><div className="modal"><div style={{display:'flex',justifyContent:'space-between'}}><h2>Settings</h2><button className="iconbtn" onClick={()=>setSettings(false)}><X/></button></div><div className="field"><label>Display name</label><input value={user.name} onChange={e=>{const next={...user,name:e.target.value};setUser(next);localStorage.setItem('zoom_user',JSON.stringify(next));localStorage.setItem('zoom_name',e.target.value)}}/></div><div className="field"><label>Email</label><input value={user.email} disabled/></div><div className="modalActions"><button className="primary" onClick={()=>setSettings(false)}>Save</button></div></div></div>}{toast&&<div className="toast">{toast}</div>}</div>
}
