'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api, User } from '@/lib/api';
export default function Schedule(){
const router=useRouter();const [user,setUser]=useState<User|null>(null);const [topic,setTopic]=useState('My Meeting');const [description,setDescription]=useState('');const [showDescription,setShowDescription]=useState(false);const [date,setDate]=useState('');const [time,setTime]=useState('11:30');const [period,setPeriod]=useState('AM');const [hours,setHours]=useState('0');const [minutes,setMinutes]=useState('40');const [zone,setZone]=useState('local');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
useEffect(()=>{try{const raw=localStorage.getItem('zoom_user');if(!raw){router.replace('/login');return}setUser(JSON.parse(raw));const n=new Date();setDate(`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-${String(n.getDate()).padStart(2,'0')}`)}catch{router.replace('/login')}},[router]);
async function save(){if(!user)return;setError('');const duration=Number(hours)*60+Number(minutes);if(!topic.trim()||!date||!time||duration<1){setError('Enter a topic, date, time, and a duration of at least one minute.');return}const [h,m]=time.split(':').map(Number);if(h<1||h>12||m<0||m>59){setError('Enter a valid time between 1:00 and 12:59.');return}const hh=h%12+(period==='PM'?12:0);const stamp=`${date}T${String(hh).padStart(2,'0')}:${String(m).padStart(2,'0')}:00`;const when=new Date(zone==='local'?stamp:stamp+zone);if(!Number.isFinite(when.getTime())){setError('Choose a valid date and time.');return}setBusy(true);try{await api.create({title:topic.trim(),description,scheduled_at:when.toISOString(),duration_minutes:duration,host_name:user.name,owner_user_id:user.id,is_scheduled:true});router.push('/')}catch(e){setError((e as Error).message);setBusy(false)}}
if(!user)return null;
return <main className="schedulePage"><button className="scheduleBack" onClick={()=>router.push('/')}>❮ Back to Meetings</button><h1>Schedule Meeting</h1><form onSubmit={e=>{e.preventDefault();void save()}}><div className="scheduleRow"><label htmlFor="topic"><span className="required">*</span> Topic</label><div><input id="topic" maxLength={120} required value={topic} onChange={e=>setTopic(e.target.value)}/>{showDescription?<textarea aria-label="Description" maxLength={1000} rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Enter a description"/>:<button type="button" className="textLink addDescription" onClick={()=>setShowDescription(true)}>＋ Add Description</button>}</div></div><div className="scheduleRow"><label htmlFor="schedule-date">When</label><div className="scheduleInline"><input id="schedule-date" required type="date" value={date} onChange={e=>setDate(e.target.value)}/><input aria-label="Start time" placeholder="11:30" value={time} onChange={e=>setTime(e.target.value)}/><select aria-label="AM or PM" value={period} onChange={e=>setPeriod(e.target.value)}><option>AM</option><option>PM</option></select></div></div><div className="scheduleRow"><label>Duration</label><div className="scheduleInline durationInline"><select aria-label="Duration hours" value={hours} onChange={e=>setHours(e.target.value)}>{Array.from({length:24},(_,i)=><option key={i}>{i}</option>)}</select><span>hr</span><select aria-label="Duration minutes" value={minutes} onChange={e=>setMinutes(e.target.value)}>{['0','15','30','40','45','50','55'].map(n=><option key={n}>{n}</option>)}</select><span>min</span></div></div><div className="scheduleRow"><label htmlFor="schedule-zone">Time Zone</label><select id="schedule-zone" value={zone} onChange={e=>setZone(e.target.value)}><option value="local">Local time ({Intl.DateTimeFormat().resolvedOptions().timeZone})</option><option value="+05:30">(GMT+5:30) India</option><option value="Z">(GMT+0:00) UTC</option></select></div><div className="scheduleRow"><label>Meeting ID</label><div><label className="scheduleChoice"><input type="radio" checked readOnly/> Generate Automatically</label></div></div>{error&&<p role="alert" className="scheduleError">{error}</p>}<div className="scheduleActions"><button className="primary" disabled={busy}>{busy?'Saving…':'Save'}</button><button type="button" className="secondary" onClick={()=>router.push('/')}>Cancel</button></div></form></main>}
