'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import AuthArtwork from '@/components/AuthArtwork';
import ZoomWordmark from '@/components/ZoomWordmark';
import { X, Video, Pencil, MessageSquare, MonitorUp, Users } from 'lucide-react';
import { api } from '@/lib/api';

export default function Login(){
 const router=useRouter();
 const [step,setStep]=useState<'email'|'password'>('email');const [help,setHelp]=useState(false);
 const [mode,setMode]=useState<'login'|'register'>('login');
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const go=async()=>{setError('');if(!email.trim()||password.length<6)return setError('Enter an email and a password of at least 6 characters.');setBusy(true);try{const r=mode==='login'?await api.login({email,password}):await api.register({email,password,name});localStorage.removeItem('zoom_signed_out');localStorage.setItem('zoom_user',JSON.stringify(r.user));localStorage.setItem('zoom_name',r.user.name);const meetingId=new URLSearchParams(window.location.search).get('meeting');if(meetingId&&/^\d[\d -]*$/.test(meetingId)){router.replace(`/meeting/${meetingId.replace(/[ -]/g,'')}?name=${encodeURIComponent(r.user.name)}&userId=${r.user.id}`)}else{router.push('/')}}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const changeMode=(next:'login'|'register')=>{setMode(next);setStep('email');setError('');};
 const next=()=>{if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email.trim())){setError('Enter a valid email address.');return;}setError('');setStep('password');};
 return <div className={`authPage ${mode==='register'?'signupPage':'signinPage'}`}>
 <header className="authHeader"><span className="zoomWordmark"><ZoomWordmark/></span><nav>{mode==='login'&&<span>New to Zoom? <button onClick={()=>changeMode('register')}>Sign Up Free</button></span>}<button onClick={()=>setHelp(true)}>Support</button></nav></header>
 <main className="authMain"><section className="authVisual">{mode==='login'?<AuthArtwork/>:<div className="signupBenefits"><h2>Create your free basic<br/>account</h2><p><Video size={23}/>Meet face to face with camera and audio</p><p><Pencil size={23}/>Capture your meeting notes</p><p><MessageSquare size={23}/>Stay connected with meeting group chat</p><p><MonitorUp size={23}/>Share your screen and keep your video visible</p><p><Users size={23}/>Bring everyone together in one meeting</p></div>}</section>
 <section className="authFormRegion"><div className="authForm"><h1>{mode==='register'?'Sign up for free':'Sign in'}</h1>{mode==='register'&&<p className="authSubtitle">No credit card required</p>}
 {mode==='login'?<>{step==='email'?<><div className="field"><label className="srOnly" htmlFor="auth-email">Email</label><input id="auth-email" autoFocus type="email" placeholder="Enter email address" value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==='Enter'&&next()}/></div><button className="primary authSubmit" onClick={next}>Next</button></>:<><button className="authEmailBack" onClick={()=>setStep('email')}>{email} · Edit</button><div className="field"><label htmlFor="auth-password">Password</label><input id="auth-password" autoFocus type="password" placeholder="At least 6 characters" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()}/></div><button className="primary authSubmit" disabled={busy} onClick={go}>{busy?'Signing in…':'Sign in'}</button></>}</>:<><div className="field"><label htmlFor="register-name">Display name</label><input id="register-name" placeholder="e.g. Alex Sharma" value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label htmlFor="register-email">Enter your email address</label><input id="register-email" type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field"><label htmlFor="register-password">Password</label><input id="register-password" type="password" placeholder="At least 6 characters" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()}/></div><button className="primary authSubmit" disabled={busy} onClick={go}>{busy?'Creating account…':'Continue'}</button></>}
 {error&&<p className="authError" role="alert">{error}</p>}<div className="authSwitch">{mode==='login'?<>Don’t have an account? <button onClick={()=>changeMode('register')}>Sign up for free</button></>:<>Already have an account? <button onClick={()=>changeMode('login')}>Sign In</button></>}</div><p className="authPrivacy">Your meetings, notes, and conversations.<br/>All in one place.</p></div></section></main>
 {help&&<div className="modalBackdrop"><div className="modal"><div className="utilityHeading"><h2>Sign-in help</h2><button aria-label="Close sign-in help" className="iconbtn" onClick={()=>setHelp(false)}><X size={20}/></button></div><p>Use your email and password to sign in. If you do not have an account, choose Sign up for free. You can also join an invite link as a guest without signing in.</p><button className="primary" onClick={()=>setHelp(false)}>Got it</button></div></div>}
 </div>
}
