'use client';
import { useEffect, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Camera, CameraOff, ChevronLeft, Mic, MicOff, UserRound } from 'lucide-react';
import { api, Meeting, User } from '@/lib/api';
export default function InviteJoin(){
 const {id}=useParams<{id:string}>();const router=useRouter();
 const [name,setName]=useState('');const [meeting,setMeeting]=useState<Meeting|null>(null);const [error,setError]=useState('');const [user,setUser]=useState<User|null>(null);const [remember,setRemember]=useState(false);const [muted,setMuted]=useState(true);const [cameraOff,setCameraOff]=useState(true);const [mediaError,setMediaError]=useState('');const [mediaBusy,setMediaBusy]=useState(false);
 const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const mounted=useRef(true);
 const stopPreview=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null};
 useEffect(()=>{mounted.current=true;try{const raw=localStorage.getItem('zoom_user');const saved=localStorage.getItem('zoom_remembered_name');if(raw){const u=JSON.parse(raw) as User;setUser(u);setName(saved||u.name)}else if(saved)setName(saved);setRemember(Boolean(saved))}catch{}api.meeting(id).then(m=>{if(mounted.current)setMeeting(m)}).catch(e=>{if(mounted.current)setError((e as Error).message)});return()=>{mounted.current=false;stopPreview()}},[id]);
 const back=()=>{stopPreview();router.push(user?'/':`/login?meeting=${encodeURIComponent(id)}`)};
 async function toggleMedia(kind:'audio'|'video'){
  if(mediaBusy)return;const enabling=kind==='audio'?muted:cameraOff;const tracks=kind==='audio'?stream.current?.getAudioTracks():stream.current?.getVideoTracks();setMediaError('');
  if(enabling&&!tracks?.length){setMediaBusy(true);try{const acquired=await navigator.mediaDevices.getUserMedia(kind==='audio'?{audio:true}:{video:true});if(!mounted.current){acquired.getTracks().forEach(t=>t.stop());return}if(!stream.current)stream.current=new MediaStream();acquired.getTracks().forEach(t=>stream.current!.addTrack(t));if(video.current)video.current.srcObject=stream.current}catch{setMediaError(`Unable to access your ${kind==='audio'?'microphone':'camera'}. Check browser permissions.`);return}finally{if(mounted.current)setMediaBusy(false)}}
  (kind==='audio'?stream.current?.getAudioTracks():stream.current?.getVideoTracks())?.forEach(t=>t.enabled=enabling);if(kind==='audio')setMuted(!enabling);else setCameraOff(!enabling);
 }
 const join=()=>{const n=name.trim();if(!n)return;if(remember)localStorage.setItem('zoom_remembered_name',n);else localStorage.removeItem('zoom_remembered_name');localStorage.setItem('zoom_name',n);stopPreview();router.push(`/meeting/${id}?name=${encodeURIComponent(n)}&userId=${user?.id||0}&muted=${muted?'1':'0'}&cameraOff=${cameraOff?'1':'0'}`)};
 if(error)return <div className="invalidMeeting"><button onClick={back}>❮ Back</button><h1>{error==='Meeting not found'?'This meeting link is invalid (3,001)':'Unable to load the meeting. Please try again.'}</h1></div>;
 if(!meeting)return <div className="joiningScreen"><div><span className="joiningSpinner"/><p>Joining Meeting...</p></div></div>;
 return <main className="prejoinPage"><button className="prejoinBack" onClick={back}><ChevronLeft size={16}/>Back</button><div className="prejoinLayout"><section className="prejoinPreview" aria-label="Camera preview"><video ref={video} autoPlay muted playsInline style={{visibility:cameraOff?'hidden':'visible'}}/>{cameraOff&&<div className="prejoinAvatar"><UserRound size={116} strokeWidth={0} fill="currentColor"/></div>}<div className="prejoinControls"><button disabled={mediaBusy} aria-label={muted?'Unmute':'Mute'} onClick={()=>void toggleMedia('audio')}>{muted?<MicOff/>:<Mic/>}<span>{muted?'Unmute':'Mute'}</span></button><button disabled={mediaBusy} aria-label={cameraOff?'Start Video':'Stop Video'} onClick={()=>void toggleMedia('video')}>{cameraOff?<CameraOff/>:<Camera/>}<span>{cameraOff?'Start Video':'Stop Video'}</span></button></div></section><form className="prejoinForm" onSubmit={e=>{e.preventDefault();join()}}><h1>Enter Meeting Info</h1><label htmlFor="guest-name">Your Name</label><input id="guest-name" autoFocus maxLength={80} value={name} onChange={e=>setName(e.target.value)}/><label className="prejoinRemember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Remember my name for future meetings</label><button className="prejoinJoin" disabled={!name.trim()||mediaBusy}>Join</button>{mediaError&&<p className="prejoinError" role="alert">{mediaError}</p>}</form></div></main>;
}
